### ISSUE TITLE
Implement async/await interface

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metalog#106]
Implement async/await interface in addition to events and callbacks.
- [x] Constructor `const logger = await new Logger();`
- [x] Open `await logger.open();`
- [x] Close `await logger.close();`
- [ ] Rotate `await logger.rotate();`

**Comment by Bob-chemist** [comment]
Can you, please, give a hint on implementation of async/await in constructor?

**Comment by Bob-chemist** [comment]
> Can you, please, give a hint on implementation of async/await in constructor?

I've found it in your "Async programming" course. 
But I still can't understand - does "in addition" mean that we will be able to call constructor and other methods both inside async functions and in synchronous code?
E.g.?: 
```
(async () => {
    const logger2 = await new Logger();
})();

const logger3 = new Logger();
```

**Comment by tshemsedinov** [comment]
See this for example: https://github.com/metarhia/config/blob/master/config.js#L11
You can call it `const config = await new Config(path);`

**Comment by tshemsedinov** [comment]
If we return promise from constructor we definitely need to wrap `await new` into async function
