### ISSUE TITLE
An issue with disabling the file system

### ISSUE THREAD

**Issue by ChngYrNick** [metarhia/metalog#218]
**Describe the bug**
When you disable the file system in the configuration by defining the 'toFile' param with an empty array, it still tries to create a log folder or read a log file from it.

**To Reproduce**
1. Delete the 'log' folder from the root of the project or ensure it's not there;
2. Set the 'toFile' property with an empty array inside of config;
3. Run the program.

**Expected behavior**
The log folder doesn't create

**Actual behavior**
The log folder present at the root of the project

**Desktop (please complete the following information):**

- OS: macOS 13.1
- Node.js version 16.15.1

**Comment by tshemsedinov** [comment]
Thanks for reporting this important problem!

**Comment by tshemsedinov** [comment]
Done: https://github.com/metarhia/metalog/pull/219
