### ISSUE TITLE
Fix single argument functions

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metalog#53]
Remove parentheses around single argument arrow functions

**Comment by jn-lp** [comment]
Hello, i'm student of IP-85 group, ready to complete this task

**Comment by tshemsedinov** [comment]
Please don't open PRs before assignment to an issue, @jn-lp

**Comment by tshemsedinov** [comment]
Take an invitation to be assigned

**Comment by tshemsedinov** [comment]
Are you going to implement this? @jn-lp

**Comment by jn-lp** [comment]
@tshemsedinov, shame on me, can You explain the process of accepting invitation to be assigned?
